export const campgroundSeeds = [
  {
    title: "Mazury Lake Retreat",
    city: "Giżycko",
    street: "Leśna",
    houseNumber: "12",
    location: "Giżycko, warmińsko-mazurskie",
    coordinates: [21.7644, 54.0381],
    price: 180,
    type: "lake",
  },
  {
    title: "Wild Lake Camp",
    city: "Mikołajki",
    street: "Jeziorna",
    houseNumber: "8",
    location: "Mikołajki, warmińsko-mazurskie",
    coordinates: [21.5701, 53.8029],
    price: 210,
    type: "lake",
  },
  {
    title: "Forest Bay Camping",
    city: "Ruciane-Nida",
    street: "Leśna",
    houseNumber: "24",
    location: "Ruciane-Nida, warmińsko-mazurskie",
    coordinates: [21.5396, 53.6414],
    price: 160,
    type: "lake",
  },
  {
    title: "Masurian Pines",
    city: "Mrągowo",
    street: "Brzozowa",
    houseNumber: "17",
    location: "Mrągowo, warmińsko-mazurskie",
    coordinates: [21.3051, 53.8644],
    price: 145,
    type: "forest",
  },
  {
    title: "Northern Lake Hideaway",
    city: "Węgorzewo",
    street: "Polna",
    houseNumber: "7",
    location: "Węgorzewo, warmińsko-mazurskie",
    coordinates: [21.7372, 54.2157],
    price: 170,
    type: "lake",
  },

  {
    title: "Solina Lakeside Camp",
    city: "Solina",
    street: "Bieszczadzka",
    houseNumber: "31",
    location: "Solina, podkarpackie",
    coordinates: [22.4592, 49.3996],
    price: 220,
    type: "mountain",
  },
  {
    title: "Bieszczady Wilderness",
    city: "Wetlina",
    street: "Wetlina",
    houseNumber: "82",
    location: "Wetlina, podkarpackie",
    coordinates: [22.4715, 49.1247],
    price: 190,
    type: "mountain",
  },
  {
    title: "Cisna Forest Camp",
    city: "Cisna",
    street: "Leśna",
    houseNumber: "16",
    location: "Cisna, podkarpackie",
    coordinates: [22.3274, 49.2134],
    price: 175,
    type: "forest",
  },
  {
    title: "Bieszczady Valley",
    city: "Ustrzyki Dolne",
    street: "Górska",
    houseNumber: "21",
    location: "Ustrzyki Dolne, podkarpackie",
    coordinates: [22.5943, 49.4301],
    price: 165,
    type: "mountain",
  },
  {
    title: "Polańczyk Lake Escape",
    city: "Polańczyk",
    street: "Zdrojowa",
    houseNumber: "19",
    location: "Polańczyk, podkarpackie",
    coordinates: [22.4212, 49.3694],
    price: 225,
    type: "lake",
  },

  {
    title: "Tatra Base Camp",
    city: "Kościelisko",
    street: "Nędzy Kubińca",
    houseNumber: "42",
    location: "Kościelisko, małopolskie",
    coordinates: [19.8897, 49.2904],
    price: 260,
    type: "mountain",
  },
  {
    title: "Podhale Mountain Camp",
    city: "Bukowina Tatrzańska",
    street: "Tatrzańska",
    houseNumber: "35",
    location: "Bukowina Tatrzańska, małopolskie",
    coordinates: [20.1085, 49.3438],
    price: 240,
    type: "mountain",
  },
  {
    title: "Mountain Meadow",
    city: "Białka Tatrzańska",
    street: "Środkowa",
    houseNumber: "84",
    location: "Białka Tatrzańska, małopolskie",
    coordinates: [20.1051, 49.3896],
    price: 245,
    type: "mountain",
  },
  {
    title: "Zakopane Forest Escape",
    city: "Zakopane",
    street: "Droga do Olczy",
    houseNumber: "26",
    location: "Zakopane, małopolskie",
    coordinates: [19.9816, 49.2992],
    price: 280,
    type: "mountain",
  },

  {
    title: "Karkonosze Forest Camp",
    city: "Karpacz",
    street: "Leśna",
    houseNumber: "13",
    location: "Karpacz, dolnośląskie",
    coordinates: [15.7554, 50.7759],
    price: 215,
    type: "mountain",
  },
  {
    title: "Giant Mountains Retreat",
    city: "Szklarska Poręba",
    street: "Turystyczna",
    houseNumber: "22",
    location: "Szklarska Poręba, dolnośląskie",
    coordinates: [15.5227, 50.8274],
    price: 205,
    type: "mountain",
  },
  {
    title: "Sudety Valley Camp",
    city: "Jelenia Góra",
    street: "Sudecka",
    houseNumber: "41",
    location: "Jelenia Góra, dolnośląskie",
    coordinates: [15.7395, 50.8787],
    price: 150,
    type: "forest",
  },

  {
    title: "Baltic Pines",
    city: "Łeba",
    street: "Turystyczna",
    houseNumber: "18",
    location: "Łeba, pomorskie",
    coordinates: [17.5558, 54.7601],
    price: 240,
    type: "coast",
  },
  {
    title: "Hel Peninsula Camp",
    city: "Hel",
    street: "Leśna",
    houseNumber: "6",
    location: "Hel, pomorskie",
    coordinates: [18.8013, 54.6084],
    price: 260,
    type: "coast",
  },
  {
    title: "Baltic Surf Camp",
    city: "Jastarnia",
    street: "Polna",
    houseNumber: "14",
    location: "Jastarnia, pomorskie",
    coordinates: [18.6773, 54.6967],
    price: 285,
    type: "coast",
  },
  {
    title: "Northern Beach Camp",
    city: "Władysławowo",
    street: "Żeromskiego",
    houseNumber: "28",
    location: "Władysławowo, pomorskie",
    coordinates: [18.4084, 54.7909],
    price: 235,
    type: "coast",
  },
  {
    title: "Dębki Forest & Sea",
    city: "Dębki",
    street: "Leśna",
    houseNumber: "11",
    location: "Dębki, pomorskie",
    coordinates: [18.0868, 54.8284],
    price: 255,
    type: "coast",
  },
  {
    title: "West Coast Camp",
    city: "Rewal",
    street: "Topolowa",
    houseNumber: "9",
    location: "Rewal, zachodniopomorskie",
    coordinates: [15.0146, 54.081],
    price: 230,
    type: "coast",
  },

  {
    title: "Kashubian Lake Camp",
    city: "Chmielno",
    street: "Jeziorna",
    houseNumber: "15",
    location: "Chmielno, pomorskie",
    coordinates: [18.0981, 54.3258],
    price: 165,
    type: "lake",
  },
  {
    title: "Wdzydze Wilderness",
    city: "Wdzydze",
    street: "Leśna",
    houseNumber: "20",
    location: "Wdzydze, pomorskie",
    coordinates: [17.9188, 54.013],
    price: 180,
    type: "lake",
  },
  {
    title: "Kaszuby Forest Hideaway",
    city: "Kościerzyna",
    street: "Leśna",
    houseNumber: "27",
    location: "Kościerzyna, pomorskie",
    coordinates: [17.9819, 54.1223],
    price: 145,
    type: "forest",
  },

  {
    title: "Wigry Forest Camp",
    city: "Stary Folwark",
    street: "Wigierska",
    houseNumber: "13",
    location: "Stary Folwark, podlaskie",
    coordinates: [23.086, 54.073],
    price: 155,
    type: "lake",
  },
  {
    title: "Augustów Lake Camp",
    city: "Augustów",
    street: "Turystyczna",
    houseNumber: "24",
    location: "Augustów, podlaskie",
    coordinates: [22.9796, 53.8434],
    price: 170,
    type: "lake",
  },
  {
    title: "Suwalszczyzna Wild Camp",
    city: "Suwałki",
    street: "Leśna",
    houseNumber: "33",
    location: "Suwałki, podlaskie",
    coordinates: [22.9307, 54.1115],
    price: 135,
    type: "forest",
  },

  {
    title: "Bory Tucholskie Camp",
    city: "Tuchola",
    street: "Leśna",
    houseNumber: "37",
    location: "Tuchola, kujawsko-pomorskie",
    coordinates: [17.8591, 53.5872],
    price: 135,
    type: "forest",
  },
  {
    title: "Charzykowy Lake Retreat",
    city: "Charzykowy",
    street: "Jeziorna",
    houseNumber: "21",
    location: "Charzykowy, pomorskie",
    coordinates: [17.5038, 53.735],
    price: 175,
    type: "lake",
  },

  {
    title: "Roztocze Forest Camp",
    city: "Zwierzyniec",
    street: "Leśna",
    houseNumber: "16",
    location: "Zwierzyniec, lubelskie",
    coordinates: [22.9757, 50.6146],
    price: 145,
    type: "forest",
  },
  {
    title: "Krasnobród Nature Camp",
    city: "Krasnobród",
    street: "Leśna",
    houseNumber: "25",
    location: "Krasnobród, lubelskie",
    coordinates: [23.2137, 50.5455],
    price: 150,
    type: "forest",
  },

  {
    title: "Pieniny River Camp",
    city: "Szczawnica",
    street: "Pienińska",
    houseNumber: "36",
    location: "Szczawnica, małopolskie",
    coordinates: [20.4849, 49.4244],
    price: 210,
    type: "mountain",
  },
  {
    title: "Three Crowns Camp",
    city: "Krościenko nad Dunajcem",
    street: "Zdrojowa",
    houseNumber: "18",
    location: "Krościenko nad Dunajcem, małopolskie",
    coordinates: [20.4268, 49.4405],
    price: 195,
    type: "mountain",
  },

  {
    title: "Beskid Mountain Camp",
    city: "Szczyrk",
    street: "Górska",
    houseNumber: "42",
    location: "Szczyrk, śląskie",
    coordinates: [19.0319, 49.7186],
    price: 205,
    type: "mountain",
  },
  {
    title: "Wisła Forest Retreat",
    city: "Wisła",
    street: "Leśna",
    houseNumber: "31",
    location: "Wisła, śląskie",
    coordinates: [18.8591, 49.6542],
    price: 190,
    type: "mountain",
  },
  {
    title: "Beskid Meadow",
    city: "Ustroń",
    street: "Źródlana",
    houseNumber: "17",
    location: "Ustroń, śląskie",
    coordinates: [18.8126, 49.7215],
    price: 175,
    type: "mountain",
  },

  {
    title: "Jura Rocks Camp",
    city: "Ogrodzieniec",
    street: "Leśna",
    houseNumber: "14",
    location: "Ogrodzieniec, śląskie",
    coordinates: [19.5199, 50.4511],
    price: 155,
    type: "forest",
  },
  {
    title: "Jura Forest Base",
    city: "Olsztyn",
    street: "Kuhna",
    houseNumber: "22",
    location: "Olsztyn, śląskie",
    coordinates: [19.2678, 50.7519],
    price: 145,
    type: "forest",
  },

  {
    title: "Powidz Lake Camp",
    city: "Powidz",
    street: "Jeziorna",
    houseNumber: "11",
    location: "Powidz, wielkopolskie",
    coordinates: [17.9194, 52.4127],
    price: 165,
    type: "lake",
  },
  {
    title: "Boszkowo Summer Camp",
    city: "Boszkowo",
    street: "Turystyczna",
    houseNumber: "29",
    location: "Boszkowo, wielkopolskie",
    coordinates: [16.324, 51.952],
    price: 175,
    type: "lake",
  },
  {
    title: "Sieraków Forest Camp",
    city: "Sieraków",
    street: "Leśna",
    houseNumber: "20",
    location: "Sieraków, wielkopolskie",
    coordinates: [16.0807, 52.6502],
    price: 140,
    type: "forest",
  },

  {
    title: "Łagów Lake Hideaway",
    city: "Łagów",
    street: "Leśna",
    houseNumber: "8",
    location: "Łagów, lubuskie",
    coordinates: [15.2968, 52.3341],
    price: 165,
    type: "lake",
  },
  {
    title: "Lubuskie Forest Camp",
    city: "Niesulice",
    street: "Jeziorna",
    houseNumber: "19",
    location: "Niesulice, lubuskie",
    coordinates: [15.3805, 52.1905],
    price: 150,
    type: "lake",
  },

  {
    title: "Drawsko Wild Lake",
    city: "Czaplinek",
    street: "Leśna",
    houseNumber: "28",
    location: "Czaplinek, zachodniopomorskie",
    coordinates: [16.2336, 53.5579],
    price: 150,
    type: "lake",
  },
  {
    title: "Drawa Forest Retreat",
    city: "Drawsko Pomorskie",
    street: "Leśna",
    houseNumber: "35",
    location: "Drawsko Pomorskie, zachodniopomorskie",
    coordinates: [15.8098, 53.5308],
    price: 140,
    type: "forest",
  },

  {
    title: "Dolina Baryczy Camp",
    city: "Milicz",
    street: "Leśna",
    houseNumber: "26",
    location: "Milicz, dolnośląskie",
    coordinates: [17.2714, 51.5277],
    price: 135,
    type: "forest",
  },
  {
    title: "Barycz Nature Retreat",
    city: "Żmigród",
    street: "Polna",
    houseNumber: "17",
    location: "Żmigród, dolnośląskie",
    coordinates: [16.9054, 51.4669],
    price: 130,
    type: "forest",
  },

  {
    title: "Zegrze Lakeside",
    city: "Serock",
    street: "Jeziorna",
    houseNumber: "23",
    location: "Serock, mazowieckie",
    coordinates: [21.0694, 52.5102],
    price: 185,
    type: "lake",
  },
  {
    title: "Kampinos Forest Camp",
    city: "Kampinos",
    street: "Leśna",
    houseNumber: "15",
    location: "Kampinos, mazowieckie",
    coordinates: [20.4637, 52.2688],
    price: 145,
    type: "forest",
  },
];
